<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-Q18VUQ5U" name="tests.GroupActivityReportTest" tests="27" failures="0" timestamp="13 Apr 2020 11:01:28 GMT" time="0.061" errors="27">
  <testcase name="advancedFilterForGroupName" time="0.004" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- advancedFilterForGroupName -->
  <testcase name="paginationCountVerification" time="0.001" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- paginationCountVerification -->
  <testcase name="advancedFilterUI" time="0.001" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- advancedFilterUI -->
  <testcase name="dateRangeFilterForYesterday" time="0.004" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- dateRangeFilterForYesterday -->
  <testcase name="dateRangeFilterForLast30Days" time="0.001" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- dateRangeFilterForLast30Days -->
  <testcase name="advancedFilterForLeads" time="0.001" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- advancedFilterForLeads -->
  <testcase name="paginationToolboxUIVerification" time="0.005" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- paginationToolboxUIVerification -->
  <testcase name="advancedFilterForCalls" time="0.000" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- advancedFilterForCalls -->
  <testcase name="allColumnPickerCheckboxesClickable" time="0.003" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- allColumnPickerCheckboxesClickable -->
  <testcase name="secondaryGroupingFeatureForCampaignColumn" time="0.000" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- secondaryGroupingFeatureForCampaignColumn -->
  <testcase name="tableCountVerification" time="0.004" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- tableCountVerification -->
  <testcase name="secondaryGroupingFeatureForTrackingNumber" time="0.000" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- secondaryGroupingFeatureForTrackingNumber -->
  <testcase name="secondaryGroupingFeatureForCampaign" time="0.005" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- secondaryGroupingFeatureForCampaign -->
  <testcase name="advancedFilterForAnweredCalls" time="0.004" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- advancedFilterForAnweredCalls -->
  <testcase name="secondaryGroupingOptions" time="0.002" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- secondaryGroupingOptions -->
  <testcase name="defaultColumnsDisplayed" time="0.002" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- defaultColumnsDisplayed -->
  <testcase name="dateRangeFilterForLast7Days" time="0.003" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- dateRangeFilterForLast7Days -->
  <testcase name="secondaryGroupingFeatureForTrackingumberColumn" time="0.009" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- secondaryGroupingFeatureForTrackingumberColumn -->
  <testcase name="dateRangeFilterForToday" time="0.004" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- dateRangeFilterForToday -->
  <testcase name="secondaryGroupingFeatureForNone" time="0.000" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- secondaryGroupingFeatureForNone -->
  <testcase name="uiVerification" time="0.004" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- uiVerification -->
  <testcase name="defaultSecondaryGroupingOption" time="0.000" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- defaultSecondaryGroupingOption -->
  <testcase name="advancedFilterForConversion" time="0.000" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- advancedFilterForConversion -->
  <testcase name="tileCountVerification" time="0.001" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- tileCountVerification -->
  <testcase name="basicFilterForGroupName" time="0.000" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- basicFilterForGroupName -->
  <testcase name="defaultColumnPickerOptions" time="0.003" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- defaultColumnPickerOptions -->
  <testcase name="dateRangeFilterUIVerification" time="0.000" classname="tests.GroupActivityReportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TrackingNumberBuilderPage.trackingNumberCreationVerification(TrackingNumberBuilderPage.java:941)
	at pom.TrackingNumberBuilderPage.createSimpleNumber(TrackingNumberBuilderPage.java:1822)
	at testdata.TestDataCreation.createTrackingNumber(TestDataCreation.java:115)
	at testdata.TestData.createData(TestData.java:45)
	at tests.TestBase.setUp(TestBase.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- dateRangeFilterUIVerification -->
</testsuite> <!-- tests.GroupActivityReportTest -->
